# Generated by Django 4.2.6 on 2023-10-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='test',
            new_name='text',
        ),
    ]
