# Generated by Django 4.2.6 on 2024-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0003_category_test_feedback_created_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('succeeded', models.IntegerField(default=0)),
                ('students', models.IntegerField(default=0)),
                ('teachers', models.IntegerField(default=0)),
                ('awards', models.IntegerField(default=0)),
            ],
        ),
    ]
