# Generated by Django 4.2.6 on 2024-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0006_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default=1, upload_to='', verbose_name='media/category'),
            preserve_default=False,
        ),
    ]
