# Generated by Django 4.2.6 on 2024-03-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0009_alter_category_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
    ]
