# Generated by Django 4.2.6 on 2024-03-06 04:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0011_alter_test_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
