# Generated by Django 4.2.6 on 2024-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0012_alter_article_body_alter_category_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='body',
            field=models.TextField(),
        ),
    ]
