# Generated by Django 4.2.6 on 2024-03-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0013_alter_article_body_alter_category_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default=1, upload_to='test/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='summary',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='donwapp.test'),
        ),
    ]
