# Generated by Django 4.2.6 on 2024-03-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0014_test_image_test_summary_alter_answer_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='donwapp.langcategory'),
        ),
    ]
