# Generated by Django 4.2.6 on 2024-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donwapp', '0016_test_correct_test_incorrert1_test_incorrert2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='test',
            name='incorrert1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='incorrert2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='incorrert3',
        ),
    ]
